### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by Thomashighbaugh** [meain/dotfiles#4]
First off, I really love how thorough this repo is. Personally had to split mine into a mess of repos for my own sanity but having them all in one place is pretty awesome. 

Just maybe consider abstracting the top level of the repo into sub-directories of some arbitrary nature to make the repo less daunting to look at and I bet you will be trending in no time! Cause this is one thorough and complete set up right here great work.

**Comment by meain** [comment]
Thanks. Glad you found it useful. :)

Right now every top level folder is a specific "program"(for the most part). If I were to subdivide it, it is mostly going to be completely arbitrary ones apart from ones like `shells`, `editors` and `linters`.

To be frank I just put it up so that I can link people to bits of my config or clone it somewhere else without password. I started off with a few files and just realized that it is a relatively big list of files now, but I don't really plan on spending a lot of time to organize or document much of it as of now.
